[supabase]
url="https://xzqbpyioyauogsvyikjz.supabase.co"
key="xzqbpyioyauogsvyikjz"

RAZORPAY_KEY_ID = "rzp_test_Swr4hAoIDvmzOa"
RAZORPAY_KEY_SECRET = "BmxROUU75eO24iawqk9n2TbZ"
WEBHOOK_SECRET = "dummy"