[supabase]
url="https://xzqbpyioyauogsvyikjz.supabase.co"
key="xzqbpyioyauogsvyikjz"

RAZORPAY_KEY_ID = "rzp_test_Swr4hAoIDvmzOa"
RAZORPAY_KEY_SECRET = "BmxROUU75eO24iawqk9n2TbZ"
WEBHOOK_SECRET = "dummy"

OPENAI_API_KEY="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"
